# Generated by Django 6.0.6 on 2026-07-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloRol',
            fields=[
                ('Estado', models.BooleanField(db_column='Estado', default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='ModeloTipoIdentificacion',
            fields=[
                ('Estado', models.BooleanField(db_column='Estado', default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
                ('Abreviatura', models.CharField(db_column='Abreviatura', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Identificación',
                'verbose_name_plural': 'Tipos de Identificación',
                'db_table': 'Tipo_Identificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModeloUsuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('Estado', models.BooleanField(db_column='Estado', default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('Telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('NumeroIdentificacion', models.CharField(db_column='NumeroIdentificacion', max_length=20, unique=True)),
                ('Correo', models.EmailField(db_column='Correo', max_length=100, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('TipoIdentificacion', models.ForeignKey(db_column='TipoIdentificacion', on_delete=django.db.models.deletion.PROTECT, to='APLICACION_USUARIOS.modelotipoidentificacion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='ModeloRolUsuario',
            fields=[
                ('Estado', models.BooleanField(db_column='Estado', default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Rol', models.ForeignKey(db_column='Rol', on_delete=django.db.models.deletion.CASCADE, related_name='UsuariosRol', to='APLICACION_USUARIOS.modelorol')),
                ('Usuario', models.ForeignKey(db_column='Usuario', on_delete=django.db.models.deletion.CASCADE, related_name='RolesUsuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roles Usuario',
                'verbose_name_plural': 'Roles Usuarios',
                'db_table': 'Rol_Usuario',
                'constraints': [models.UniqueConstraint(fields=('Usuario', 'Rol'), name='UniqueUsuarioRol')],
                'unique_together': {('Usuario', 'Rol')},
            },
        ),
    ]
