# Generated by Django 6.0.6 on 2026-07-24 05:58

import APLICACION_EMPRESA.models.RutasGuardado
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDepartamento',
            fields=[
                ('Estado', models.BooleanField(db_column='Estado', default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
                ('Codigo', models.CharField(default=0, max_length=5, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEmpresa',
            fields=[
                ('Estado', models.BooleanField(db_column='Estado', default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Nit', models.CharField(db_column='Nit', max_length=20, unique=True)),
                ('RazonSocial', models.CharField(db_column='RazonSocial', max_length=200)),
                ('Logo', models.ImageField(blank=True, db_column='Logo', null=True, upload_to=APLICACION_EMPRESA.models.RutasGuardado.RutaLogoEmpresa)),
                ('Direccion', models.CharField(db_column='Direccion', max_length=250)),
                ('Barrio', models.CharField(db_column='Barrio', max_length=100)),
                ('Telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('Correo', models.EmailField(db_column='Correo', max_length=254)),
                ('CuposHora', models.PositiveSmallIntegerField(db_column='CuposHora', default=1)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Empresa',
                'ordering': ['RazonSocial'],
            },
        ),
        migrations.CreateModel(
            name='ModeloMunicipio',
            fields=[
                ('Estado', models.BooleanField(db_column='Estado', default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=120)),
                ('Codigo', models.CharField(default=0, max_length=5, unique=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'Municipio',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloServicio',
            fields=[
                ('Estado', models.BooleanField(db_column='Estado', default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloServicioEmpresa',
            fields=[
                ('Estado', models.BooleanField(db_column='Estado', default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Servicio Empresa',
                'verbose_name_plural': 'Servicios Empresa',
                'db_table': 'ServiciosEmpresa',
            },
        ),
        migrations.CreateModel(
            name='ModeloTipoEmpresa',
            fields=[
                ('Estado', models.BooleanField(db_column='Estado', default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Empresa',
                'verbose_name_plural': 'Tipos de Empresa',
                'db_table': 'TipoEmpresa',
                'ordering': ['Nombre'],
            },
        ),
    ]
