# Generated by Django 6.0.6 on 2026-07-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APLICACION_EMPRESA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloempresa',
            name='Administrador',
            field=models.ForeignKey(db_column='Administrador', on_delete=django.db.models.deletion.PROTECT, related_name='Empresas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelomunicipio',
            name='Departamento',
            field=models.ForeignKey(db_column='Departamento', on_delete=django.db.models.deletion.PROTECT, related_name='Municipios', to='APLICACION_EMPRESA.modelodepartamento'),
        ),
        migrations.AddField(
            model_name='modeloempresa',
            name='Municipio',
            field=models.ForeignKey(db_column='Municipio', on_delete=django.db.models.deletion.PROTECT, related_name='Empresas', to='APLICACION_EMPRESA.modelomunicipio'),
        ),
        migrations.AddField(
            model_name='modeloservicioempresa',
            name='Empresa',
            field=models.ForeignKey(db_column='Empresa', on_delete=django.db.models.deletion.CASCADE, related_name='Servicios', to='APLICACION_EMPRESA.modeloempresa'),
        ),
        migrations.AddField(
            model_name='modeloservicioempresa',
            name='Servicio',
            field=models.ForeignKey(db_column='Servicio', on_delete=django.db.models.deletion.PROTECT, related_name='Empresas', to='APLICACION_EMPRESA.modeloservicio'),
        ),
        migrations.AddField(
            model_name='modeloempresa',
            name='TipoEmpresa',
            field=models.ForeignKey(db_column='TipoEmpresa', on_delete=django.db.models.deletion.PROTECT, related_name='Empresas', to='APLICACION_EMPRESA.modelotipoempresa'),
        ),
        migrations.AlterUniqueTogether(
            name='modelomunicipio',
            unique_together={('Nombre', 'Departamento')},
        ),
        migrations.AlterUniqueTogether(
            name='modeloservicioempresa',
            unique_together={('Empresa', 'Servicio')},
        ),
    ]
