from .SerializadorDepartamentoResumen import SerializadorDepartamentoResumen
from .SerializadorMunicipioResumen import SerializadorMunicipioResumen
from .SerializadorMunicipioResumenDepartamento import SerializadorMunicipioResumenDepartamento
from .SerializadorServicioResumen import SerializadorServicioResumen
from .SerializadorTipoEmpresaResumen import SerializadorTipoEmpresaResumen
from .SerializadorEmpresaResumen import SerializadorEmpresaResumen
from .SerializadorEmpresaResumenServicio import SerializadorEmpresaResumenServicio